### ISSUE TITLE
Fail after upgrade logstash to 8.10.X

### ISSUE THREAD

**Issue by dr4gon123** [logstash-plugins/logstash-filter-tld#25] opened 2023-10-21 13:09 UTC
I just upgraded to logstash 8.10.4, and now tld plugin throws this error. I have also have a report that it is failing on logstash 8.10.1

[2023-10-21T07:52:42,131][ERROR][logstash.javapipeline    ][syslog-fortinet-common_ecs-output] Pipeline error {:pipeline_id=>"syslog-fortinet-common_ecs-output", :exception=>#<ArgumentError: wrong number of arguments (given 2, expected 1)>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/public_suffix-3.1.1/lib/public_suffix/list.rb:69:in parse'", "/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/public_suffix-3.1.1/lib/public_suffix/list.rb:51:in default'", "/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-filter-tld-3.1.2/lib/logstash/filters/tld.rb:33:in register'", "org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:75:in register'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:237:in block in register_plugins'", "org/jruby/RubyArray.java:1987:in each'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:236:in register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:611:in maybe_setup_out_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:249:in start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:194:in run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:146:in `block in start'"], "pipeline.sources"=>["central pipeline management"], :thread=>"#<Thread:0x1540f398 /usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:134 run>"}

it used to work just fine. 

The logstash pipeline where I am using it is:

https://github.com/enotspe/fortinet-2-elasticsearch/blob/master/logstash/conf.d/syslog-fortinet-common_ecs-output.conf#L214

**Comment by edmocosta** [comment] 2023-10-23 08:48
Hey @enotspe!

Thank you for reporting this issue. Could you please confirm if you're using the latest plugin version [3.1.3](https://rubygems.org/gems/logstash-filter-tld/versions/3.1.3)? If that's not the case, upgrading should fix this problem:
```shell
bin/logstash-plugin install --version 3.1.3 logstash-filter-tld
```

**Comment by dr4gon123** [comment] 2023-10-23 15:01
I was using 3.1.2. I will upgrade and let you know

**Comment by dr4gon123** [comment] 2023-10-23 15:08
it does not seem to ugprade to 3.1.3

```
[ec2-user@ip-172-30-3-33 ~]$ cd /usr/share/logstash
[ec2-user@ip-172-30-3-33 logstash]$ sudo systemctl stop logstash
[ec2-user@ip-172-30-3-33 logstash]$ sudo bin/logstash-plugin install --version 3.1.3 logstash-filter-tld
Using bundled JDK: /usr/share/logstash/jdk
io/console on JRuby shells out to stty for most operations
Validating logstash-filter-tld-3.1.3
Resolving mixin dependencies
Installing logstash-filter-tld
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core":
  In Gemfile:
    logstash-core-plugin-api was resolved to 2.1.16, which depends on
      logstash-core (= 8.10.4)

    logstash-input-twitter was resolved to 1.0.1, which depends on
      logstash-core (< 2.0.0, >= 1.4.0)

```

**Comment by edmocosta** [comment] 2023-10-24 13:10
Hi @enotspe!

This new issue seems to be caused by the twitter input plugin, which unfortunately wasn't fixed yet (https://github.com/logstash-plugins/logstash-input-twitter/issues/76) to work with Logstash 8.10+.

If you're not using it, removing this plugin should work as an alternative solution:
```
bin/logstash-plugin remove logstash-input-twitter 
```
And then
```
bin/logstash-plugin install --version 3.1.3 logstash-filter-tld
```

**Comment by dr4gon123** [comment] 2023-10-24 16:33
Thanks!!! Installation worked fine now

```
[ec2-user@ip-172-30-3-33 ~]$  cd /usr/share/logstash
[ec2-user@ip-172-30-3-33 logstash]$ sudo bin/logstash-plugin remove logstash-input-twitter 
Using bundled JDK: /usr/share/logstash/jdk
io/console on JRuby shells out to stty for most operations
Resolving dependencies.................................................................................................................................................................................................................
Resolving dependencies...........................................................
Successfully removed logstash-input-twitter
[ec2-user@ip-172-30-3-33 logstash]$ sudo bin/logstash-plugin install --version 3.1.3 logstash-filter-tld
Using bundled JDK: /usr/share/logstash/jdk
io/console on JRuby shells out to stty for most operations
Validating logstash-filter-tld-3.1.3
Resolving mixin dependencies
Installing logstash-filter-tld
Installation successful
```
and now logstash works with tld!!!

**Comment by edmocosta** [comment] 2023-10-24 20:24
That's great! I'm gonna go ahead and close this issue, as this plugin problem was fixed on the latest version. Thanks!

**Closed as completed by edmocosta** 2023-10-24 20:24 UTC
Labels: bug
